### ISSUE TITLE
使用此配置严重掉帧

### ISSUE THREAD

**Issue by 245938767** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#1]
cpu：12490F
显卡：Rx6600xt蓝宝石
内存 ：2X16g
主板：MSI-B660M-D4-WIFI-MORTAR

打开视频页面观看视频，视频会严重卡顿，并且拖动页面大小也会产生严重的卡顿
跑分截图

<img width="1939" alt="图片" src="https://user-images.githubusercontent.com/51525402/186337469-bc0099ee-d033-4a0b-97c6-669207c08a0c.png">
是否有跑分截图能够让我对照一下我现在做的对不对（感觉我现在这个跑分跟我预期的低了一半）
最开始我使用您的CPUFriendDataProvider.kext文件跑分只有660，我自己又去生成一遍CPUFriendDataProvider.kext后，跑分有明显的上升(到达765)

**Comment by 245938767** [comment]
使用你EFI的方法对独显进行优化，显卡的跑分有轻微的增加
<img width="1934" alt="截屏2022-08-24 14 34 04" src="https://user-images.githubusercontent.com/51525402/186347640-9b513e7e-9def-4b6e-85cf-ad7fc5b910dd.png">

在看视频的时候还是不够流畅

**Comment by zemise** [comment]
> 

刚装完，我也有明显的卡顿感。后来我一次时间机器恢复，一次迁移助手迁移，没有出现视频和拖动卡顿。但窗口页面双击缩放，会有明显卡顿痕迹，我比较了我的白苹果MacBook pro2019(i5 2.4GHz 16G)，其也有这个现象。于是就将页面双击改为最小化，这个很流畅。

至于跑分，我和你分数差不多，只是我的显卡分比你低，毕竟我的是RX6600。CPU得分我咨询过其他人，因为12代CPU只能仿冒其他CPU才能上黑苹果，性能有被压制。

**Comment by 245938767** [comment]
使用此cpu经过多次测试发现对Kernel->add 的CpuTopologyRebuild.kext和CpuTscSync.kext禁用和最小核不录入数据，可以达到我目前测试中跑分表现最好的
<img width="2301" alt="截屏2022-08-25 19 28 15" src="https://user-images.githubusercontent.com/51525402/186661224-42f33baa-27bf-4774-b6f0-7afe3e8cee5c.png">
把所有的插件都开启后测试出来的配置

<img width="2817" alt="截屏2022-08-25 20 09 19" src="https://user-images.githubusercontent.com/51525402/186661771-fae568c0-ebab-45c3-9fe7-ebe09754aecf.png">
关闭大小核插件测试后的性能（这个u好像只有大核）

<img width="2827" alt="截屏2022-08-25 19 53 56" src="https://user-images.githubusercontent.com/51525402/186662079-695e9db5-ed5e-489f-8cd8-8c8084b80aa9.png">
关闭所有的配置后测试的性能

不知道还能往什么方向进行优化

**Comment by zemise** [comment]
对，这颗U不分大小核，我一直也很困惑它的的优化，你的这个操作和我今天更新的EFI一模一样，一样也是取消了勾选，只是我的机器在测试跑分时，并无太多变化，有时单核跑分甚至更低了。

**Comment by 245938767** [comment]
> 对，这颗U不分大小核，我一直也很困惑它的的优化，你的这个操作和我今天更新的EFI一模一样，一样也是取消了勾选，只是我的机器在测试跑分时，并无太多变化，有时单核跑分甚至更低了。

 platforminfo->dataHUb-Generic-platformNVRAM->processorType(自定义CPU型号) 
我修改了如上配置也会提高我的cpu运行时的测试分数，使用更高级的cpuID

**Comment by zemise** [comment]
> > 对，这颗U不分大小核，我一直也很困惑它的的优化，你的这个操作和我今天更新的EFI一模一样，一样也是取消了勾选，只是我的机器在测试跑分时，并无太多变化，有时单核跑分甚至更低了。
> 
> platforminfo->dataHUb-Generic-platformNVRAM->processorType(自定义CPU型号) 我修改了如上配置也会提高我的cpu运行时的测试分数，使用更高级的cpuID
我之前写的型号是1537，请问你后来改的是哪个型号？

**Comment by 245938767** [comment]
> > > 对，这颗U不分大小核，我一直也很困惑它的的优化，你的这个操作和我今天更新的EFI一模一样，一样也是取消了勾选，只是我的机器在测试跑分时，并无太多变化，有时单核跑分甚至更低了。
> > 
> > 
> > platforminfo->dataHUb-Generic-platformNVRAM->processorType(自定义CPU型号) 我修改了如上配置也会提高我的cpu运行时的测试分数，使用更高级的cpuID
> > 我之前写的型号是1537，请问你后来改的是哪个型号？

你可以使用1578或者参考其他相同的cpu的型号配置（但是我在配置后在测试中发现其提升比较有限，我cpu跑分最高到达1000上下）

**Comment by zemise** [comment]
> > > > 对，这颗U不分大小核，我一直也很困惑它的的优化，你的这个操作和我今天更新的EFI一模一样，一样也是取消了勾选，只是我的机器在测试跑分时，并无太多变化，有时单核跑分甚至更低了。
> > > 
> > > 
> > > platforminfo->dataHUb-Generic-platformNVRAM->processorType(自定义CPU型号) 我修改了如上配置也会提高我的cpu运行时的测试分数，使用更高级的cpuID
> > > 我之前写的型号是1537，请问你后来改的是哪个型号？
> 
> 你可以使用1578或者参考其他相同的cpu的型号配置（但是我在配置后在测试中发现其提升比较有限，我cpu跑分最高到达1000上下）

em.....反复尝试了多次，变化还是不大，偶尔有跑到1000，但这跑分不稳定。跑分这方面算了，不纠结了。日常使用中唯一让我不舒服的就是鼠标缩放窗口时，有掉帧感，在白果笔记本上也有类似情况，可能黑果大屏幕下放大了这种情况。

**Comment by yiguo-bj** [comment]
hello，机器配置和仓库的主人一模一样，请问这个 EFI 还有卡顿掉帧的问题吗？可以直接使用 macOS 13.01 的镜像吗？

**Comment by zemise** [comment]
> hello，机器配置和仓库的主人一模一样，请问这个 EFI 还有卡顿掉帧的问题吗？可以直接使用 macOS 13.01 的镜像吗？

没有卡顿掉帧问题了，很流畅。
可以直接使用13.01
