### ISSUE TITLE
Wifi无法发现热点

### ISSUE THREAD

**Issue by Gxsh71** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#10]
您好，我和您的配置是一样的，按照您的OC进行了安装（Ventura），目前其他的都可以正常工作，主要有两个问题，一个是CPU信息无法正常显示，这个倒是无关紧要，另一个就是intel AX211的wifi问题，系统看到wifi已经开启，网卡也能看到（包括网卡的Mac地址信息），但是就是在wifi里面看不到任何热点SSID,AirportItlwm.kext我是2.1和2.2版本都试过，结果是一样的。我看您的截图wifi列表中是正常显示SSID的。不知道这个wifi设置有什么特别需要关注的？

**Comment by Gxsh71** [comment]
已经自己解决

**Comment by cws-24** [comment]
> 已经自己解决了

兄弟怎么解决的

**Comment by cws-24** [comment]
> 已经自己解决了

兄弟怎么解决的？

**Comment by Gxsh71** [comment]
> 
因为也是不太熟悉黑苹果，自己看了网站，学习了一些知识。感觉还是自己要做USB的map，但是我最初确实是自己做的USB map。反正是做了两次，第二次做完了，重新启动，然后出现wifi图标后，又等了很久，再打开wifi面板就搜索到热点了
