### ISSUE TITLE
使用v1.5安装Ventura 13.4,卡eb是什么情况？

### ISSUE THREAD

**Issue by Wgga** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#11]
处理器                 12th Gen Intel Core i5-12490F 六核
  主板                   微星 Mac-AA95B1DDAB278B95（LPC Controller/eSPI Controller B660芯片组）
  显卡                   NVIDIA GeForce GTX 1050 Ti ( 4 GB / 七彩虹 )
  内存                   16 GB ( 朗科科技 DDR4 3200MHz 8GB x 2 )
  主硬盘                 西数 WD_BLACK SN770 500GB (500 GB / 固态硬盘)
  显示器                 QTF QTF2700 ( 27 英寸  )
  声卡                   瑞昱  @ 英特尔 High Definition Audio 控制器
  网卡                   英特尔 Wi-Fi 6E AX211 160MHz
  
  
  使用v1.5版本安装的Ventura 13.4，进入oc引导后选择安装mac，然后就卡eb代码了，bios该设置的也设置了，该怎么解决呀

**Comment by zemise** [comment]
> 处理器                 12th Gen Intel Core i5-12490F 六核
> 
>   主板                   微星 Mac-AA95B1DDAB278B95（LPC Controller/eSPI Controller B660芯片组）
> 
>   显卡                   NVIDIA GeForce GTX 1050 Ti ( 4 GB / 七彩虹 )
> 
>   内存                   16 GB ( 朗科科技 DDR4 3200MHz 8GB x 2 )
> 
>   主硬盘                 西数 WD_BLACK SN770 500GB (500 GB / 固态硬盘)
> 
>   显示器                 QTF QTF2700 ( 27 英寸  )
> 
>   声卡                   瑞昱  @ 英特尔 High Definition Audio 控制器
> 
>   网卡                   英特尔 Wi-Fi 6E AX211 160MHz
> 
>   
> 
>   
> 
>   使用v1.5版本安装的Ventura 13.4，进入oc引导后选择安装mac，然后就卡eb代码了，bios该设置的也设置了，该怎么解决呀

硬件上来说，显卡不对，我的配置是AMD显卡的，是免驱的

**Comment by Wgga** [comment]
> > 处理器 第12代英特尔酷睿i5-12490F 六核
> > 主板                   微星 Mac-AA95B1DDAB278B95（LPC Controller/eSPI Controller B660芯片组）
> > 显卡 NVIDIA GeForce GTX 1050 Ti （ 4 GB / 七彩虹 ）
> > 内存 16 GB （ 朗科科技 DDR4 3200MHz 8GB x 2 ）
> > 主硬盘 西数 WD_BLACK SN770 500GB （500 GB / 固态硬盘）
> > 显示器 QTF QTF2700 （ 27 英寸 ）
> > 声卡                   瑞昱  @ 英特尔 High Definition Audio 控制器
> > 网卡                   英特尔 Wi-Fi 6E AX211 160MHz
> > 使用v1.5版本安装的Ventura 13.4，进入oc引导后选择安装mac，然后就卡eb代码了，bios该设置的也设置了，该怎么解决呀
> 
> 硬件上来说，显卡不对，我的配置是AMD显卡的，是免驱的

如果在您的配置调整的话好调整吗？或者制作一个符合我配置的？重新制作的话，您这边有教程吗？

**Comment by zemise** [comment]
> 如果在您的配置调整的话好调整吗？或者制作一个符合我配置的？重新制作的话，您这边有教程吗？

精力有限，只能管自己的这套配置。
教程参考国光黑苹果教程：https://apple.sqlsec.com
其实板U相同，随意搭一个免驱的显卡是很快就装上黑苹果的
