### ISSUE TITLE
我在使用EFI发现的一些问题

### ISSUE THREAD

**Issue by zhanniuniu** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#12]
我的配置是下面这样的，基本是照着配置的硬件
CPU：Intel i5 12490F
主板：MSI-B660M-D4-WIFI-MORTAR
显卡：华硕AMD RX6600
内存： 光威 威龙D45 16G DDR4 3200MHz*2
MacOS盘： 西数sn770-2T
win10盘： 三星970Evo-2T
WiFi + BT: Intel AX211

在安装黑苹果13.4时，发现了一下问题：
1、卡EB，最终是通过设置setupvirtualmap，为ture解决的
2、EFI放在硬盘，无法在硬盘启动，最终是删除无用的文件，保留boot和oc解决
3、WiFi失效，无法发现WiFi，通过更新WiFi相关kext文件解决
4、蓝牙失效，关闭后无法开启，也无法正常连接，目前没解决（通过网上教程更新相关设置，更新kext还是没解决）
5、彻底息屏，主机睡眠，重新唤醒后，会出现声音关闭现象，未解决

下次更新希望可以给解决一下

**Comment by zemise** [comment]
> 我的配置是下面这样的，基本是照着配置的硬件
> 
> CPU：Intel i5 12490F
> 
> 主板：MSI-B660M-D4-WIFI-MORTAR
> 
> 显卡：华硕AMD RX6600
> 
> 内存： 光威 威龙D45 16G DDR4 3200MHz*2
> 
> MacOS盘： 西数sn770-2T
> 
> win10盘： 三星970Evo-2T
> 
> WiFi + BT: Intel AX211
> 
> 
> 
> 在安装黑苹果13.4时，发现了一下问题：
> 
> 1、卡EB，最终是通过设置setupvirtualmap，为ture解决的
> 
> 2、EFI放在硬盘，无法在硬盘启动，最终是删除无用的文件，保留boot和oc解决
> 
> 3、WiFi失效，无法发现WiFi，通过更新WiFi相关kext文件解决
> 
> 4、蓝牙失效，关闭后无法开启，也无法正常连接，目前没解决（通过网上教程更新相关设置，更新kext还是没解决）
> 
> 5、彻底息屏，主机睡眠，重新唤醒后，会出现声音关闭现象，未解决
> 
> 
> 
> 下次更新希望可以给解决一下
> 
> 

非常好的issue，其中的一些问题，我会在下一次更新时，重点关注着重解决一下

**Comment by litttleP** [comment]
蓝牙的问题我解决了，参考的是这个链接，他那个下载链接，之前一直有问题，最近才好了
https://www.bilibili.com/read/cv24122599/

**Comment by kaelorgo** [comment]
这个配置能支持完美睡眠吗？

**Comment by litttleP** [comment]
这个EFI似乎内置的声卡驱动设置在我电脑上也存在问题，表现为音频输入只有显示器的，没有内置的，外置音箱直接插到电脑上没有输出。我的声卡为ALCS1200A，我的具体修改为找到EFI文件下面的OC文件夹，修改config文件，在boot-args下面，将alcid=66改为11，目前音频正常，声音关闭打不开的问题也没有再出现。在未改以前，视频输出换DP口，可以解决声音关闭的问题。问题修改参考这个连接http://www.imacosx.cn/7263.html

**Comment by zemise** [comment]
> 这个EFI似乎内置的声卡驱动设置在我电脑上也存在问题，表现为音频输入只有显示器的，没有内置的，外置音箱直接插到电脑上没有输出。我的声卡为ALCS1200A，我的具体修改为找到EFI文件下面的OC文件夹，修改config文件，在boot-args下面，将alcid=66改为11，目前音频正常，声音关闭打不开的问题也没有再出现。在未改以前，视频输出换DP口，可以解决声音关闭的问题。问题修改参考这个连接http://www.imacosx.cn/7263.html

谢谢，已经更新EFI，蓝牙和声卡问题已解决

**Comment by zemise** [comment]
> 这个配置能支持完美睡眠吗？

在之前的一个版本中，睡眠有点小问题：即能睡眠，也能正常外设唤醒，但是机械硬盘有反复启动的声响。最近更新了EFI，还需要观察下

**Comment by zemise** [comment]
> > 这个配置能支持完美睡眠吗？
> 
> 在之前的一个版本中，睡眠有点小问题：即能睡眠，也能正常外设唤醒，但是机械硬盘有反复启动的声响。最近更新了EFI，还需要观察下

已解决，完美睡眠

**Comment by zemise** [comment]
Done
