### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by cleardid** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#13]
博主你好,我和你的配置一模一样,但是加载了你的efi文件开机直接卡在白logo界面,请问是不是有其他需要注意的地方,望回复,感谢

**Comment by zemise** [comment]
你好，不好意思，最近太忙。在最新的EFI文件中只保留了OC和boot文件夹，可自行替换即可

**Comment by zemise** [comment]
> 博主你好,我和你的配置一模一样,但是加载了你的efi文件开机直接卡在白logo界面,请问是不是有其他需要注意的地方,望回复,感谢

你好，不好意思，最近太忙。在最新的EFI文件中只保留了OC和boot文件夹，可自行替换即可
