### ISSUE TITLE
内存少一点，显卡是6600xt，跑分才要少很多。

### ISSUE THREAD

**Issue by dayn97** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#14]
<img width="319" alt="iShot_2023-07-26_11 25 52" src="https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/47072414/d5885c86-3ae0-4cb6-8b4f-e69c01a10181">
<img width="892" alt="iShot_2023-07-26_11 26 34" src="https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/47072414/b837b8fd-7e76-4a9a-85ff-6d00c8aab75f">

**Comment by zemise** [comment]
@dayn97 今天我更新了的EFI，以及更新系统到13.5，我的跑分如下，仅供参考。
<img width="864" alt="image" src="https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/46216418/aebd1766-79cf-4640-8628-d5af237b3885">
我一般积极的更新系统，私以为每个版本和不同的驱动，导致跑分变动是正常的。一般系统流畅不卡，其实不用太在意跑分

**Comment by dayn97** [comment]
系统很流畅，只是原无线网卡无法开启，开启就会卡死，换了博通的pcie免驱网卡。感谢作者的付出。
