### ISSUE TITLE
重启

### ISSUE THREAD

**Issue by yeshuang112233** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#15]
大佬，我跟你配置完全一样，但是使用你的efi开启会卡在读条开始的时候，然后重启，一直重复进不了系统是什么原因啊，bios也是照你的设置了

**Comment by zemise** [comment]
> 大佬，我跟你配置完全一样，但是使用你的efi开启会卡在读条开始的时候，然后重启，一直重复进不了系统是什么原因啊，bios也是照你的设置了

你加上一个-v参数，看看具体表现的错误是什么

**Comment by yeshuang112233** [comment]
![931690857055_ pic](https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/111287210/97367c26-33a2-46ad-afb0-d320938128f2)

**Comment by yeshuang112233** [comment]
我现在是12.6.6，就下的你的v1.3版本

**Comment by zemise** [comment]
> 我现在是12.6.6，就下的你的v1.3版本

图上显示的wake-failure的错误，有可能是AMD Radeon Rx5/6000系黑屏幕错误，可以试试
NVRAM -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 ->boot-args
agdpmod=pikera

不过看到你说的还在用12.6的版本，我的建议是直接采用最新的EFI和系统

**Comment by yeshuang112233** [comment]
我主要是不喜欢13系统的界面，所以一直停留在12，我也试过你最新的那个版本，就是卡进度条，重启，我再拍一个你看看

**Comment by yeshuang112233** [comment]
![941690858679_ pic](https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/111287210/036637c7-b7d6-4f3f-be4f-743a1ddb1454)

**Comment by zemise** [comment]
@yeshuang112233 你可以先用这个https://github.com/SuperNG6/MSI-B660-Monterey-EFI 的AMD General GPU版EFI试试，看看是否有同样错误

**Comment by yeshuang112233** [comment]
![951690859900_ pic](https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/111287210/92209e9c-11a1-4b56-aaf0-a06db5ab28d2)
我用那个General GPU版本的就是这样的，感觉问题主要就是在显卡上

**Comment by zemise** [comment]
> 我用那个General GPU版本的就是这样的，感觉问题主要就是在显卡上

- 显卡如果是6600，本身是免驱的，只是常见的问题为黑屏，表现为安装过程中黑屏，但是主机并不会关。
- 这套EFI的前提是主板bios版本为7D42v13，如果不是，也有可能引发一些未知错误，你可以检查下版本

**Comment by yeshuang112233** [comment]
好的，我再去看看bios

**Comment by passwii** [comment]
Hi, 你解决问题了吗？我也碰到这个同样的EB界面

**Comment by zemise** [comment]
> Hi, 你解决问题了吗？我也碰到这个同样的EB界面

先定制下USB

**Comment by zemise** [comment]
#19 麻烦参照这条
