### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by yiiyk022** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#16]
我想问一下如果是主板和CPU不一样 
EFI需要改吗 主板是MSI PRO B660M-A WIFI DDR4
网卡应该是一样的AX211 CPU是i3 12100F

>

**Comment by zemise** [comment]
> 我想问一下如果是主板和CPU不一样
> EFI需要改吗 主板是MSI PRO B660M-A WIFI DDR4
> 网卡应该是一样的AX211 CPU是i3 12100F

黑苹果首要考虑的硬件就三样，主板、CPU、显卡，如果不一样，EFI一般不能通用。你可以先试试，因为你这个主板和我的相近
