### ISSUE TITLE
连接WIFI重启问题

### ISSUE THREAD

**Issue by cws-24** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#17]
我的配置：
主板也是迫击炮WIFI版+i5-12400+N卡 1080ti
铁汁有遇到一连接WIFI就重启的问题么。

**Comment by cws-24** [comment]
换了13.3的版本。直接搜不到网络了。。。。

**Comment by prankchild** [comment]
> 我的配置： 主板也是迫击炮WIFI版+i5-12400+N卡 1080ti 铁汁有遇到一连接WIFI就重启的问题么。

我也是这个问题，请问你解决了吗

**Comment by zemise** [comment]
> 我也是这个问题，请问你解决了吗


勾选了我取消的kext么，最近我用的是博通的网卡

**Comment by prankchild** [comment]
> 



> > 我也是这个问题，请问你解决了吗
> 
> 勾选了我取消的kext么，最近我用的是博通的网卡

用了你之前的版本 就是没有博通网卡的那个版本也会出现这个问题

**Comment by zemise** [comment]
> 用了你之前的版本 就是没有博通网卡的那个版本也会出现这个问题

定制下自己的USB

**Comment by zemise** [comment]
#19  麻烦参照这条
