### ISSUE TITLE
Wi-Fi 无法使用，以及一些其他可能会有用的信息

### ISSUE THREAD

**Issue by 8Q757** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#19]
已经安装成功，目前看了一下**Wi-Fi无法搜索到信号**，其他还没具体测试，希望有朋友可以提供一些参考。
惊讶的是，睡眠竟然正常，我甚至没有在`Kernel`中勾选`HibernationFixup.kext`。

CPU/主板/显卡与该项目一致
内存: 英睿达 16GB 3200Mhz * 2 
硬盘: 西数黑盘 SN770 1TB

一些可能会对其他人有用的信息：

- 微星主板 bios 需要更新到 7D42v13 版本，这里是  [下载链接](https://www.msi.cn/Motherboard/MAG-B660M-MORTAR-WIFI-DDR4/support)
> 这并不一定是一个必需条件，因为我没有经过充分的对照测试，但确实在两个独立信息源都看到了这种说法，但我确实是在升级改版本后安装成功(但同时也改动了一部分efi，所以并不能完全确认)，希望可以加入到 README 中

**Comment by 8Q757** [comment]
看到作者提到已经替换了博通网卡，使用英特尔网卡需要手动勾选回 efi，但是clone下来看到 英特尔相关网卡 已经是默认勾选的

![image](https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/28482172/467247c5-8cf4-48d2-a9e7-2cc1e0fbe51c)


另外，似乎没有看到作者定制之后的 `USBPort.kext`。

感谢作者的efi🙏

**Comment by zemise** [comment]
> 看到作者提到已经替换了博通网卡，使用英特尔网卡需要手动勾选回 efi，但是clone下来看到 英特尔相关网卡 已经是默认勾选的

感谢写的很详细，最近大家出现的WiFi无法连接现象，我其实也挺困惑的。因为以前使用这个EFI的人并没有出现这种情况。

1. 你所说到的BIOS版本，的确是有影响的，**最初制作这款EFI时，7D42v13版本才能顺利安装黑苹果，7D42v17版本不行**，这点我明确测试过，也在其他issue里提到过，之后我再README再强调下，最近新出现的WiFi连接问题，可能是新买主板的bios版本不再是7D42v13。

2. clone下的版本是上一个版本，所以 英特尔相关网卡已经是默认勾选的，而且那个版本我没有出现睡眠问题。release的新版本，USBPort.kext有定制，但是这个版本我用的博通网卡，出现了睡眠不完美。

**Comment by zemise** [comment]
#17 #15 #18
