### ISSUE TITLE
点击安装时没有进度条

### ISSUE THREAD

**Issue by 1248499257** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#2]
配置:
cpu: 12490f
主板: 华硕b660m wifi d4
内存：16 * 2
显卡: 5500x5

请问我需要把efi上的显卡配置改成我自己的吗，还有 cfg lock 在bios上好像找不到入口关闭，望指教～

**Comment by zemise** [comment]
1、显卡免驱的话，可以先不用改
2、cfg这个我当时也找了半天，后来百度找到位置的，你是华硕可能和我的微星也有点不一样
3、点击安装，如果是指刚开始引导的话，可以添加-v这个跑码参数，一般EFI成功后都取消了这个

**Comment by 1248499257** [comment]
> 1、显卡免驱的话，可以先不用改 2、cfg这个我当时也找了半天，后来百度找到位置的，你是华硕可能和我的微星也有点不一样 3、点击安装，如果是指刚开始引导的话，可以添加-v这个跑码参数，一般EFI成功后都取消了这个

后续我花了几十块找了个人远程安装了一下，不知道还是不是安装方式不对，进去黑苹果之后用一会就开始重启（卖家说不要安装软件在系统盘，装在桌面，我试了还是这样），最后我进windows也会重启了，寄！

**Comment by zemise** [comment]
> > 1、显卡免驱的话，可以先不用改 2、cfg这个我当时也找了半天，后来百度找到位置的，你是华硕可能和我的微星也有点不一样 3、点击安装，如果是指刚开始引导的话，可以添加-v这个跑码参数，一般EFI成功后都取消了这个
> 
> 后续我花了几十块找了个人远程安装了一下，不知道还是不是安装方式不对，进去黑苹果之后用一会就开始重启（卖家说不要安装软件在系统盘，装在桌面，我试了还是这样），最后我进windows也会重启了，寄！

找卖家吧，花了钱那自然得让他弄好才是

**Comment by 1248499257** [comment]
> > > 1、显卡免驱的话，可以先不用改 2、cfg这个我当时也找了半天，后来百度找到位置的，你是华硕可能和我的微星也有点不一样 3、点击安装，如果是指刚开始引导的话，可以添加-v这个跑码参数，一般EFI成功后都取消了这个
> > 
> > 
> > 后续我花了几十块找了个人远程安装了一下，不知道还是不是安装方式不对，进去黑苹果之后用一会就开始重启（卖家说不要安装软件在系统盘，装在桌面，我试了还是这样），最后我进windows也会重启了，寄！
> 
> 找卖家吧，花了钱那自然得让他弄好才是

目前也只能这样了，看卖家能不能就活～
