### ISSUE TITLE
主板自带ax211搜索wifi需要3分钟以上

### ISSUE THREAD

**Issue by Liuthx** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#20]
使用的efi为更换网卡前的release, 硬件配置一致, 蓝牙正常, wifi搜索无效, 但以前连接过的可以等到约3分钟以后连接成功, 连接成功后使用正常, 睡眠唤醒有时候可以直接连上, 有时候需要再等几分钟才行.

**Comment by zemise** [comment]
> 使用的efi为更换网卡前的release, 硬件配置一致, 蓝牙正常, wifi搜索无效, 但以前连接过的可以等到约3分钟以后连接成功, 连接成功后使用正常, 睡眠唤醒有时候可以直接连上, 有时候需要再等几分钟才行.

板载Wi-Fi在开机时启动偏慢是常见的，这点的确不如博通网卡，博通网卡在开机还没输入密码前，就已经连接上了，无论睡眠与否。
