### ISSUE TITLE
使用这个EFI，EPIC客户端会闪退

### ISSUE THREAD

**Issue by AlphaGolalala** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#22]
rt，不知道什么原因，但是换一个EFI就可以，我搜了一下 似乎与显卡有关

**Comment by zemise** [comment]
如果只是单一的客户端闪退，就不太清楚具体问题，有没有什么错误信息报告

**Comment by AlphaGolalala** [comment]
所有基于Electron 的 APP都打不开(epic、天翼云盘、百度云盘、飞书等等)。已经知道并解决问题了，加上“ipc_control_port_options=0”就好了
