### ISSUE TITLE
进系统卡在苹果图标不动了

### ISSUE THREAD

**Issue by sfwjnpw1** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#23]
我之前的是 i310100 的黑苹果，换了一样的 cpu 主板和显卡，主板 bios 版本和设置都弄好了，把以前的efi 文件直接删了把你的 efi 放上去，就卡在苹果图标不动了，是换硬件必须要重新装系统吗？谢谢了

**Comment by zemise** [comment]
具体是哪一版本的EFI，以及你可能需要定制一下USB，同时，添加-v跑码，附上详细的错误

**Comment by sfwjnpw1** [comment]
好了可以进了，更新 bios 后默认 vt-d 是打开的，我没有注意。谢谢了

**Comment by denganjia** [comment]
大佬你好，我使用了你的efi，版本为1.6，我电脑跟你是一样的，目前也是会进入系统卡苹果logo。加了-v参数后，出现错误：ACPI Warning Unsupported module-level executable opcode 0x70 at table offset。
最后一行代码就是这个，然后没反应了

**Comment by sfwjnpw1** [comment]
哥们，我不是这个 efi 的作者，如果电脑硬件的品牌完全一样，把对应的 bios 设置修改下是没有问题的。你看 bios 设置有需要修改的地方改了没有！
