### ISSUE TITLE
微星 b660 的 ax211 网卡无法使用

### ISSUE THREAD

**Issue by sfwjnpw1** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#24]
使用1.7.1 版本 efi 文件，网卡对应模块也启用了。mac 上蓝牙和 wifi 都是灰的无法使用。![截屏2024-01-04 17 20 40](https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/86069797/5584d6b0-b9f3-430f-bfe9-3bb29fd8557a)

**Comment by zemise** [comment]
你大概是漏看了这个，
<img width="992" alt="image" src="https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/46216418/645b360a-5564-4de1-a5de-81406bc0dd48">

**Comment by sfwjnpw1** [comment]
我们主板一样，应该勾选usbports.kext文件吗？我这个版本没有这个文件可勾选要版本还是自己定制

**Comment by zemise** [comment]
可以试试将新版的EFI文件中的usbports.kext文件拷贝过去，同时取消USBToolBox和UTBMap

**Comment by zemise** [comment]
<img width="1066" alt="image" src="https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/46216418/ee17e36b-53f0-499c-8793-8f6e655314db">

**Comment by zemise** [comment]
有段时间没有更新这个EFI了，我刚查看了下更新记录，你可以试试1.7的版本先

<img width="1227" alt="image" src="https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/46216418/5ec2b30b-5a31-44b6-bc87-70fef4f24018">

**Comment by sfwjnpw1** [comment]
我用的就是这个版本，但是是微星的 ax211网卡。我看了几个版本都没有 usbports 的文件

**Comment by zemise** [comment]
[USBPorts.kext.zip](https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/files/13828713/USBPorts.kext.zip)
从我电脑里拷出来的，你试试

**Comment by sfwjnpw1** [comment]
放进去勾选后无法启动了

**Comment by Cyborg2017** [comment]
@sfwjnpw1 可以尝试使用最新驱动：[releases](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.3.0-alpha)

并将ax210相关的勾选上：
<img width="946" alt="image" src="https://github.com/zemise/12490F-MSI-B660-MORTAR-WiFi-RX6600-EFI-OC/assets/29827082/c95387b3-f127-419f-b277-a71bb9803aa5">

**Comment by zemise** [comment]
参照最新EFI
