### ISSUE TITLE
最新版本没有 USBPorts.kext

### ISSUE THREAD

**Issue by Jokerman1991** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#25]
最新版本没有 USBPorts.kext，是改名成默认的 UTBMap.kext 了吗？还是忘了放？

**Comment by zemise** [comment]
[USBPorts.kext.zip](https://github.com/user-attachments/files/17405014/USBPorts.kext.zip)

**Comment by Jokerman1991** [comment]
> [USBPorts.kext.zip](https://github.com/user-attachments/files/17405014/USBPorts.kext.zip)

感谢大佬，好人一生平安~
