### ISSUE TITLE
一样的板u，显卡是rx570，安装一直卡在白苹果logo

### ISSUE THREAD

**Issue by yinan007** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#3]

**Comment by zemise** [comment]
> No description provided.

加上-v跑马参数，看看具体问题是什么，显卡不一样会有点区别

**Comment by CainLuo** [comment]
RX6600是直接免驱？

**Comment by abc408880155** [comment]
免驱，机型选7，1，防黑参数都不用

**Comment by zemise** [comment]
> RX6600是直接免驱？

免驱，机型选7，1，防黑参数都不用

**Comment by zemise** [comment]
不知道你有没有解决，最近我发现主板bios版本不一样的话，用同样的EFI会卡白苹果标志或者不跑码，微星B660的bios更新链接是https://cn.msi.com/Motherboard/MAG-B660M-MORTAR-WIFI-DDR4/support，我的这个EFI适用于bios13的那个版本

**Comment by yiguo-bj** [comment]
我也是遇到了一样的问题，最后用的是你推荐的那个安装上的。
