### ISSUE TITLE
可以试下这个efi

### ISSUE THREAD

**Issue by bre01** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#4]
我使用你的这套geekbench 5跑分大概在800，4000左右。有很多地方卡顿。
使用下面这套geekbench 5跑分大概1800，8600。动画效果非常好。

https://github.com/SuperNG6/MSI-B660-Monterey-EFI

我是没有Wi-Fi的（12490F+MSI MAG b660m MORTAR DDR4)，直接拿来用的，没有做任何修改，但是它的配置是包含了Wi-Fi的，所以我觉得你也可以直接用。(注意oc版本是 0.8.2)

**Comment by zemise** [comment]
> 我使用你的这套geekbench 5跑分大概在800，4000左右。有很多地方卡顿。 使用下面这套geekbench 5跑分大概1800，8600。动画效果非常好。
> 
> https://github.com/SuperNG6/MSI-B660-Monterey-EFI
> 
> 我是没有Wi-Fi的（12490F+MSI MAG b660m MORTAR DDR4)，直接拿来用的，没有做任何修改，但是它的配置是包含了Wi-Fi的，所以我觉得你也可以直接用。(注意oc版本是 0.8.2)

感谢提醒，我第一时间就试试了，的确非常好。跑分明显高了一倍，赞！目前只发现两个小问题，Wi-Fi蓝牙以及开机黑屏问题，这跟自己的硬件有关，后者直接关掉wtg驱动就行。我稍作调整下，哈哈

**Comment by haochengqian** [comment]
请问用https://github.com/SuperNG6/MSI-B660-Monterey-EFI这套，蓝牙除了正常的操作以外还需要什么操作才能驱动起来，我现在wifi正常驱动，蓝牙怎么都起不来

**Comment by zemise** [comment]
> 请问用https://github.com/SuperNG6/MSI-B660-Monterey-EFI这套，蓝牙除了正常的操作以外还需要什么操作才能驱动起来，我现在wifi正常驱动，蓝牙怎么都起不来

需要自行定制USB端口

**Comment by haochengqian** [comment]
谢谢，重新定制了USB以后成功了
