### ISSUE TITLE
OC 下面的 Tools 文件夹好像没有上传

### ISSUE THREAD

**Issue by yinan007** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#5]

**Comment by yinan007** [comment]
经过我的检查，OC下面的Drivers文件夹缺少文件  ResetNvramEntry.efi ToggleSipEntry.efi

**Comment by yinan007** [comment]
OC下的Kexts文件夹下缺少USBWakeFixup.kext，上传的EFI好像不完整

**Comment by yinan007** [comment]
将Kexts文件夹和Drivers文件夹的文件补齐后，在启动参数添加上agdpmod=pikera引导成功（不加会黑屏）。
另外该主板的版本需要是 7D42v13

**Comment by yinan007** [comment]
如果可以的话，可以留下联系方式,一起交流下，我也是小白玩家，咱们板U显卡一样。

**Comment by zemise** [comment]
> OC下的Kexts文件夹下缺少USBWakeFixup.kext，上传的EFI好像不完整

我的是做过修改的，少的文件是我不需要的功能，以及自己沿用自己之前定制的usb端口。在显卡RX6600下，选7，1机型，是不需要防黑屏参数的，同时也不需要whatevergreen驱动喔。

**Comment by zemise** [comment]
联系方式的话，Q吧，373933306

**Comment by Harry-AI-ass** [comment]
7D42v14可以用吗？
