### ISSUE TITLE
可以更新项目吗？

### ISSUE THREAD

**Issue by Lysant** [abc408880155/12490F-MSI-B660M-D4-WIFI-MORTAR-RX6600-EFI#9]
可以麻烦站长把现在的 efi 推上来吗？近期打算抄个作业

**Comment by abc408880155** [comment]
近期将更新到13.4

**Comment by zemise** [comment]
> 可以麻烦站长把现在的 efi 推上来吗？近期打算抄个作业

近期将更新到13.4

**Comment by abc408880155** [comment]
> 可以麻烦站长把现在的 efi 推上来吗？近期打算抄个作业

已推送最新EFI

**Comment by zemise** [comment]
> 可以麻烦站长把现在的 efi 推上来吗？近期打算抄个作业

已推送最新EFI
